### ISSUE TITLE
Add properties to Shop schema

### ISSUE THREAD

**Issue by emersonmellado** [IT-in-Canada/adoptmyshop-api#3]
Follow the docs and add missing properties to Shop schema: 

https://github.com/it-in-canada/adoptmyshop-docs#pseudo-db-schema

**Comment by bverussa** [comment]
Hey @emersonmellado 
I can't assign the issues to me and move them. Can you check the security config?

**Comment by devfernandoaraujo** [comment]
New properties added and marge done with master branch.
